'''
Created on 2015年8月10日

@author: hainan
'''
class ClasesCode(object):
    
    def __init__(self):
        pass
    
    DegreeTypeCode =   { 
      "Fatality" : 2 ,
      "Non record" : 0 ,
      "Non Hospitalized injury" : 3 ,
      "Hospitalized injury" : 1}
    
    NatureTypeCode =   { 
      "Cancer" : 0 ,
      "Strain/Sprain" : 0 ,
      "Other" : 2 ,
      "Foreign Body Ineye" : 0 ,
      "Burn(Chemical)" : 0 ,
      "Freezing/Frost Bite" : 0 ,
      "Dislocation" : 0 ,
      "Concussion" : 3 ,
      "Hearing Loss" : 0 ,
      "Poisoning(Systemic)" : 0 ,
      "Cut/Laceration" : 0 ,
      "Heat Exhaustion" : 0 ,
      "Radiation Effects" : 0 ,
      "Electric Shock" : 0 ,
      "Asphyxia" : 0 ,
      "Amputation" : 0 ,
      "Burn/Scald(Heat)" : 0 ,
      "Non record" : 0 ,
      "Bruise/Contus/Abras" : 4 ,
      "Hernia" : 0 ,
      "Puncture" : 0 ,
      "Dermatitis" : 0 ,
      "Fracture" : 1}
    
    OccupationTypeCode = {
     "Sheetmetal duct installers": 1,
     "Graders and sorters, except agricultural": 4,
     "Painting and paint spraying machine operators": 1,
     "Data processing equipment repairers": 16,
     "Supervisors; electricians & power transm. install.": 1,
     "Motor transportation occuputions n.e.c.": 10,
     "Millwrights": 1,
     "Trade and industrial teachers": 3,
     "Hoist and winch operators": 1,
     "Industrial truck and tractor equipment operators": 1,
     "Carpet installers": 5,
     "Telephone line installers and repairers": 5,
     "Telephone installers and repairers": 5,
     "Construction laborers": 15,
     "Miscellaneous plant and system operators": 1,
     "Fire inspection and fire prevention occupations": 6,
     "Operating engineers": 1,
     "Tile setters, hard and soft": 5,
     "Brickmasons and stonemasons": 2,
     "Electricians": 5,
     "Farm workers": 1,
     "Truck drivers, heavy": 7,
     "Supervisors; carpenters and related workers": 2,
     "Supervisors, n.e.c.": 4,
     "Machinery maintenance occupations": 1,
     "Assemblers": 1,
     "Technicians, n.e.c.": 2,
     "Communications equipment operators, n.e.c.": 1,
     "Management related occupations, n.e.c.": 6,
     "Plumber, pipefitter and steamfiter apprentices": 2,
     "Supervisors; distrib., sched'g & adjusting clerks": 13,
     "Crane and tower operators": 1,
     "Machine operators, not specified": 3,
     "Misc. metal,plastic,stone&glass-working; mach. op's": 10,
     "Miscellaneous hand working occupations": 4,
     "Occupational therapists": 2,
     "Supervisors, production occupations": 2,
     "Sales workers, hardware and building supplies": 18,
     "Timber cutting and logging occupations": 6,
     "Sawing machine operators": 1,
     "Managers and administrators, n.e.c": 2,
     "Not specified mechanics and repairers": 3,
     "Drillers, oil well": 11,
     "Elevator installers and repairers": 3,
     "Sheet metal workers": 1,
     "Supervisors; brickmasons, stonemasons, tilesetters": 2,
     "Janitors and cleaners": 1,
     "Supervisors and proprietors, sales occupations": 2,
     "Supervisors; handlers,equip-cleaners,laborers nec": 4,
     "Plumbers, pipefitters and steamfitters": 5,
     "Supervisors, mechanics and repairers": 1,
     "Painters, construction and maintenance": 1,
     "Mechanical engineering technicians": 1,
     "Vehicle washers and equipment cleaners": 3,
     "Freight, stock and material handlers, n.e.c.": 1,
     "Helpers, construction trades": 1,
     "Supervisors, cleaning and building service workers": 1,
     "Laborers, except construction": 15,
     "Photographers": 8,
     "Drilling and boring machine operators": 3,
     "Electrical and electronic technicians": 1,
     "Plasterers": 1,
     "Civil engineers": 9,
     "Hand packers and packagers": 1,
     "Sheet metal worker apprentices": 1,
     "Specified mechanics and repairers": 1,
     "Mechanical engineers": 1,
     "Insulation Workers": 1,
     "Engineering technicians, n.e.c.": 1,
     "Science technicians, n.e.c.": 2,
     "Concrete and terrazzo finishers": 14,
     "Glaziers": 5,
     "Supervisors, material moving equipment operators": 1,
     "Drillers, earth": 2,
     "Supervisors, extractive occupations": 2,
     "Inspectors, testers and graders": 2,
     "Political science teachers": 4,
     "Excavating and loading machine operators": 15,
     "Paving, surfacing and tamping equipment operators": 3,
     "Misc. electrical & electronic equipment repairers": 1,
     "Brickmasons and stonemasons apprentices": 1,
     "Grader, dozer and scraper operators": 3,
     "Sociology teachers": 4,
     "Structural metal workers": 1,
     "Supervisors, motor vehicle operators": 3,
     "Traffic, shipping and receiving clerks": 13,
     "Computer systems analysts and scientists": 1,
     "Sales engineers": 5,
     "Supervisors, food preparation & service occupation": 16,
     "Supervisors, forestry and logging workers": 2,
     "Optometrists": 8,
     "Miscellaneous precision woodworkers": 5,
     "Occupation not reported": 12,
     "Painters, sculptors, craft-artists & printmakers": 2,
     "Truck drivers, light": 7,
     "Helpers, extractive occupations": 2,
     "Construction inspectors": 19,
     "Bus, truck and stationary engine mechanics": 7,
     "Non record": 11,
     "Supervisors; plumbers, pipefitters & steamfitters": 2,
     "Police and detectives, public service": 9,
     "Miscellaneous precision workers, n.e.c.": 10,
     "Insurance adjusters, examiners and investigators": 9,
     "Electricians' apprentices": 2,
     "Sales occupations, other business services": 6,
     "Hand painting, coating and decorating occupations": 6,
     "Cabinet makers and bench carpenters": 5,
     "Adjusters and calibrators": 5,
     "Industrial engineers": 1,
     "Industrial engineering technicians": 1,
     "Tool and die makers": 17,
     "Electronic repairers, communica. & indus. equip.": 10,
     "Mining machine operators": 3,
     "Boilermakers": 19,
     "Helpers, mechanics and repairers": 1,
     "Hand molders and shapers, except jewelers": 1,
     "Lay-out workers": 1,
     "Lathe and turning machine set-up operators": 17,
     "Electrical power installers and repairers": 3,
     "Welders and cutters": 1,
     "Carpenters": 2,
     "Groundskeepers and gardeners, except farm": 2,
     "Managers, marketing, advertising, & public rela.": 8,
     "Sales counter clerks": 13,
     "Supervisors; painters, paperhangers and plasterers": 1,
     "Supervisors, related agricultural occupations": 4,
     "Drywall installers": 5,
     "Heavy equipment mechanics": 1,
     "Stock handlers and baggers": 3,
     "Hand cutting and trimming occupations": 6,
     "Supervisors, firefighting & fire prevention occupa": 20,
     "Production helpers": 1,
     "Precision assemblers, metal": 1,
     "Roofers": 5,
     "Miscellaneous material moving equipment operators": 1,
     "Carpenter apprentices": 1,
     "Forestry workers, except logging": 2,
     "Water and sewage treatment plant operators": 14,
     "Heating, air conditioning, and refrig. mechanics": 14,
     "Miscellaneous precision metal workers": 1,
     "Construction trades, n.e.c.": 6
    }
    
    CauseTypeCode = {
     " Loading dock forming and pouring": 13,
     " Steel Erection Of Open Web Steel Joists-Welding/Bu": 3,
     "Non record": 9,
     " Placing bridge girders and beams": 13,
     " Excavation": 6,
     " Surveying": 1,
     " Steel Erection Of Open Web Steel Joists-Landing Ma": 7,
     " Steel Erection Of Solid Web-Connecting": 4,
     " Traffic protection": 14,
     " Installation Of Decking-Initial Laying Deck (Incl": 2,
     " Stripping and curing concrete": 3,
     " Cutting concrete pavement": 3,
     " Installing metal siding": 3,
     " Landscaping": 2,
     " Installing windows and doors, glazing": 3,
     " Placing bridge deck": 5,
     " Interior carpentry": 1,
     " Interior painting and decorating": 10,
     " Installing equipment (HVAC and other)": 11,
     " Installation Of Decking-Hoisting Bundles": 12,
     " Pouring concrete floor at grade": 2,
     " Exterior masonry": 2,
     " Installation Of Decking-Final Attachment Deck (Wel": 3,
     " Exterior cladding": 3,
     " Pouring or installing floor decks": 2,
     " Steel Erection Of Open Web Steel Joists-Plumbing-U": 3,
     " Fencing, installing lights, signs, etc.": 12,
     " Elevator, escalator installation": 3,
     " Site clearing and grubbing": 10,
     " Steel Erection Of Solid Web-Landing Materials (Hoi": 5,
     " Construction of playing fields, tennis courts": 8,
     " Steel Erection Of Open Web Steel Joists-Connecting": 3,
     " Installing plumbing, lighting fixtures": 11,
     " Installing underground plumbing conduit": 12,
     " Dredging": 6,
     " Exterior carpentry": 2,
     " Steel Erection Of Solid Web-Moving Point To Point": 7,
     " Backfilling and compacting": 16,
     " Plastering": 1,
     " Waterproofing": 2,
     " Other Activities-Post Decking Detail Work": 3,
     " Steel Erection Of Solid Web-Welding/Burning/Grindi": 4,
     " Erection of coffer dams, caissons": 7,
     " Interior masonry": 3,
     " Steel Erection Of Open Web Steel Joists-Bolting-Up": 3,
     " Site grading and rock removal": 1,
     " Installing interior walls, ceilings, doors": 3,
     " Bituminous concrete placement": 3,
     " Interior plumbing, ducting, electrical work": 3,
     " Swimming pool construction": 2,
     " Paving": 2,
     " Forming for piers or pylons": 4,
     " Pile driving": 15,
     " Steel Erection Of Solid Web-Bolting-Up/Detail Work": 4,
     " Steel Erection Of Open Web Steel Joists-Moving Poi": 7,
     " Fireproofing": 11,
     " Erecting structural steel": 5,
     " Forming": 4,
     " Demolition": 6,
     " Steel Erection Of Solid Web-Plumbing-Up": 4,
     " Roofing": 2,
     " Exterior painting": 3,
     " Pouring concrete for piers, and pylons": 2,
     " Trenching, installing pipe": 11,
     " Emplacing reinforcing steel": 13,
     " Interior tile work (ceramic, vinyl, acoustic)": 2,
     " Pouring concrete foundations and walls": 2,
     " Other Activities-Installing Ornamental And Archite": 4,
     " Seawall construction, riprap placement": 5,
     " Temporary work (buildings, facilities)": 8,
     " Installing culverts and incidental drainage": 10,
     " Installation Of Decking-Flashing Of Decking": 3
    }
    
    FatCauseTypeCode = {
     " Crushed/run-over/trapped of operator by operating": 3,
     " Crushed/run-over by construction equipment during": 3,
     " Fall from/with ladder": 7,
     " Electric shock, other and unknown cause": 1,
     " Heat/hypothermia": 5,
     " Fall from vehicle (vehicle/construction equipment)": 7,
     " Fall from/with bucket (aerial lift/basket)": 7,
     " Trench collapse": 2,
     " Unloading-loading equipment/material (except by cr": 6,
     " Asphyxiation/inhalation of toxic vapor": 5,
     " Fall from/with platform catwalk (attached to struc": 7,
     " Fall through opening (other than roof)": 4,
     " Fall, other": 4,
     " Other": 1,
     " Collapse of structure": 2,
     " Crushed/run-over of non-operator by operating cons": 1,
     " Fall from roof": 2,
     "Non record": 6,
     " Wall (earthen) collapse": 2,
     " Electrocution by equipment contacting wire": 3,
     " Electrocution from equipment installation/tool use": 3,
     " Fall from/with scaffold": 7,
     " Struck by falling object/projectile": 4,
     " Drown, non-lethal fall": 4,
     " Electrocution by touching exposed wire/source": 5,
     " Elevator (struck by elevator or counter-weights)": 9,
     " Crushed/run-over by highway vehicle": 10,
     " Fall from/with structure (other than roof)": 7,
     " Lifting operations": 8,
     " Caught in stationary equipment": 3,
     " Fire/explosion": 5
    }