'''
Created on 2015年8月9日

@author: hainan
'''

class ItemClassification(object):
    '''
    classdocs
    '''


    def __init__(self):
        '''
        Constructor
        '''
        pass
    
    def get_classification(self, item_name):
        if item_name == "Degree":
            return self.degree_classification
        if item_name == "Nature":
            return self.nature_classification
        if item_name == "Occupation":
            return self.occupation_classification
        if item_name == "Cause":
            return self.cause_classification
        if item_name == "FatCause":
            return self.fat_cause_classification
        if item_name == "TaskAssigned":
            return self.task_assigned_classification
        if item_name == "HumanFactor":
            return self.human_factor_classification
        if item_name == "EnvironmentFactor":
            return self.environment_factor_classification
        if item_name == "EventType":
            return self.event_type_classification
        if item_name == "SourceInjury":
            return self.source_injury_classification
        if item_name == "PartBody":
            return self.part_body_classification
        if item_name == "ProjType":
            return self.proj_type_classification
        if item_name == "ProjCost":
            return self.proj_cost_classification
        if item_name == "EndUse":
            return self.end_use_classification
        
        return None
    
    degree_classification = { 
      "Hospitalized injury" : 6486 ,
      "Non record" : 1084 ,
      "Fatality" : 5434 ,
      "Non Hospitalized injury" : 916}     
    
    nature_classification = { 
      "Amputation" : 29 ,
      "Electric Shock" : 96 ,
      "Concussion" : 1718 ,
      "Freezing/Frost Bite" : 13 ,
      "Hearing Loss" : 2 ,
      "Radiation Effects" : 1 ,
      "Fracture" : 6422 ,
      "Puncture" : 138 ,
      "Heat Exhaustion" : 4 ,
      "Cut/Laceration" : 352 ,
      "Poisoning(Systemic)" : 3 ,
      "Dislocation" : 141 ,
      "Strain/Sprain" : 204 ,
      "Foreign Body Ineye" : 4 ,
      "Burn/Scald(Heat)" : 32 ,
      "Asphyxia" : 38 ,
      "Burn(Chemical)" : 9 ,
      "Cancer" : 14 ,
      "Non record" : 1084 ,
      "Bruise/Contus/Abras" : 1196 ,
      "Other" : 2412 ,
      "Dermatitis" : 2 ,
      "Hernia" : 6 } 
    
    
    occupation_classification = {
      "Supervisors, extractive occupations" : 1 ,
      "Misc. electrical & electronic equipment repairers" : 12 ,
      "Telephone line installers and repairers" : 28 ,
      "Inspectors, testers and graders" : 5 ,
      "Mining machine operators" : 8 ,
      "Mechanical engineering technicians" : 7 ,
      "Insulation Workers" : 35 ,
      "Supervisors; electricians & power transm. install." : 14 ,
      "Plasterers" : 135 ,
      "Supervisors, firefighting & fire prevention occupa" : 1 ,
      "Elevator installers and repairers" : 23 ,
      "Plumbers, pipefitters and steamfitters" : 120 ,
      "Supervisors, n.e.c." : 113 ,
      "Sheet metal workers" : 49 ,
      "Supervisors; distrib., sched'g & adjusting clerks" : 1 ,
      "Operating engineers" : 3 ,
      "Electricians" : 232 ,
      "Paving, surfacing and tamping equipment operators" : 12 ,
      "Communications equipment operators, n.e.c." : 7 ,
      "Vehicle washers and equipment cleaners" : 1 ,
      "Supervisors, food preparation & service occupation" : 1 ,
      "Photographers" : 1 ,
      "Miscellaneous precision woodworkers" : 2 ,
      "Sales counter clerks" : 1 ,
      "Electronic repairers, communica. & indus. equip." : 20 ,
      "Supervisors, related agricultural occupations" : 1 ,
      "Drilling and boring machine operators" : 2 ,
      "Farm workers" : 3 ,
      "Painting and paint spraying machine operators" : 8 ,
      "Occupation not reported" : 5088 ,
      "Sheetmetal duct installers" : 66 ,
      "Electrical power installers and repairers" : 81 ,
      "Drillers, earth" : 6 ,
      "Supervisors, forestry and logging workers" : 1 ,
      "Supervisors, production occupations" : 3 ,
      "Sociology teachers" : 1 ,
      "Telephone installers and repairers" : 7 ,
      "Sales occupations, other business services" : 1 ,
      "Miscellaneous precision workers, n.e.c." : 1 ,
      "Management related occupations, n.e.c." : 5 ,
      "Construction inspectors" : 8 ,
      "Supervisors, motor vehicle operators" : 2 ,
      "Engineering technicians, n.e.c." : 3 ,
      "Timber cutting and logging occupations" : 2 ,
      "Motor transportation occuputions n.e.c." : 1 ,
      "Welders and cutters" : 82 ,
      "Electricians' apprentices" : 75 ,
      "Graders and sorters, except agricultural" : 1 ,
      "Mechanical engineers" : 2 ,
      "Hoist and winch operators" : 1 ,
      "Managers, marketing, advertising, & public rela." : 1 ,
      "Precision assemblers, metal" : 4 ,
      "Lathe and turning machine set-up operators" : 2 ,
      "Helpers, construction trades" : 130 ,
      "Cabinet makers and bench carpenters" : 2 ,
      "Freight, stock and material handlers, n.e.c." : 1 ,
      "Truck drivers, light" : 2 ,
      "Miscellaneous material moving equipment operators" : 11 ,
      "Technicians, n.e.c." : 10 ,
      "Electrical and electronic technicians" : 24 ,
      "Miscellaneous hand working occupations" : 8 ,
      "Plumber, pipefitter and steamfiter apprentices" : 47 ,
      "Brickmasons and stonemasons apprentices" : 40 ,
      "Specified mechanics and repairers" : 5 ,
      "Heavy equipment mechanics" : 5 ,
      "Non record" : 851 ,
      "Supervisors and proprietors, sales occupations" : 2 ,
      "Helpers, mechanics and repairers" : 10 ,
      "Sales workers, hardware and building supplies" : 3 ,
      "Drywall installers" : 202 ,
      "Janitors and cleaners" : 6 ,
      "Supervisors; carpenters and related workers" : 169 ,
      "Excavating and loading machine operators" : 7 ,
      "Miscellaneous plant and system operators" : 1 ,
      "Supervisors; plumbers, pipefitters & steamfitters" : 20 ,
      "Sawing machine operators" : 1 ,
      "Miscellaneous precision metal workers" : 3 ,
      "Laborers, except construction" : 50 ,
      "Industrial engineering technicians" : 1 ,
      "Occupational therapists" : 1 ,
      "Production helpers" : 2 ,
      "Forestry workers, except logging" : 2 ,
      "Fire inspection and fire prevention occupations" : 2 ,
      "Sales engineers" : 2 ,
      "Insurance adjusters, examiners and investigators" : 1 ,
      "Truck drivers, heavy" : 13 ,
      "Civil engineers" : 4 ,
      "Carpenters" : 1364 ,
      "Computer systems analysts and scientists" : 1 ,
      "Supervisors; handlers,equip-cleaners,laborers nec" : 18 ,
      "Not specified mechanics and repairers" : 15 ,
      "Bus, truck and stationary engine mechanics" : 1 ,
      "Sheet metal worker apprentices" : 7 ,
      "Supervisors, cleaning and building service workers" : 3 ,
      "Assemblers" : 6 ,
      "Data processing equipment repairers" : 2 ,
      "Misc. metal,plastic,stone&glass-working; mach. op's" : 1 ,
      "Supervisors; painters, paperhangers and plasterers" : 33 ,
      "Roofers" : 1058 ,
      "Carpet installers" : 4 ,
      "Heating, air conditioning, and refrig. mechanics" : 53 ,
      "Optometrists" : 1 ,
      "Industrial truck and tractor equipment operators" : 11 ,
      "Industrial engineers" : 1 ,
      "Traffic, shipping and receiving clerks" : 1 ,
      "Concrete and terrazzo finishers" : 75 ,
      "Supervisors, mechanics and repairers" : 9 ,
      "Machine operators, not specified" : 1 ,
      "Construction trades, n.e.c." : 509 ,
      "Helpers, extractive occupations" : 3 ,
      "Lay-out workers" : 2 ,
      "Painters, sculptors, craft-artists & printmakers" : 3 ,
      "Science technicians, n.e.c." : 1 ,
      "Tool and die makers" : 1 ,
      "Stock handlers and baggers" : 1 ,
      "Boilermakers" : 14 ,
      "Grader, dozer and scraper operators" : 5 ,
      "Groundskeepers and gardeners, except farm" : 2 ,
      "Adjusters and calibrators" : 1 ,
      "Hand molders and shapers, except jewelers" : 1 ,
      "Hand cutting and trimming occupations" : 3 ,
      "Political science teachers" : 1 ,
      "Glaziers" : 30 ,
      "Drillers, oil well" : 2 ,
      "Painters, construction and maintenance" : 465 ,
      "Carpenter apprentices" : 123 ,
      "Brickmasons and stonemasons" : 162 ,
      "Supervisors, material moving equipment operators" : 1 ,
      "Police and detectives, public service" : 1 ,
      "Crane and tower operators" : 17 ,
      "Structural metal workers" : 535 ,
      "Water and sewage treatment plant operators" : 1 ,
      "Machinery maintenance occupations" : 8 ,
      "Supervisors; brickmasons, stonemasons, tilesetters" : 38 ,
      "Hand painting, coating and decorating occupations" : 7 ,
      "Construction laborers" : 1338 ,
      "Managers and administrators, n.e.c" : 8 ,
      "Trade and industrial teachers" : 1 ,
      "Millwrights" : 26 ,
      "Hand packers and packagers" : 4 ,
      "Tile setters, hard and soft" : 13} 
    
    cause_classification = { 
      " Construction of playing fields, tennis courts" : 10 ,
      " Surveying" : 16 ,
      " Fencing, installing lights, signs, etc." : 80 ,
      " Roofing" : 1511 ,
      " Installing metal siding" : 92 ,
      " Steel Erection Of Open Web Steel Joists-Plumbing-U" : 2 ,
      " Other Activities-Post Decking Detail Work" : 113 ,
      " Installing culverts and incidental drainage" : 26 ,
      " Interior carpentry" : 296 ,
      " Steel Erection Of Solid Web-Landing Materials (Hoi" : 9 ,
      " Traffic protection" : 13 ,
      " Pouring or installing floor decks" : 44 ,
      " Plastering" : 130 ,
      " Steel Erection Of Open Web Steel Joists-Welding/Bu" : 8 ,
      " Exterior painting" : 356 ,
      " Steel Erection Of Solid Web-Connecting" : 86 ,
      " Steel Erection Of Open Web Steel Joists-Connecting" : 28 ,
      " Steel Erection Of Open Web Steel Joists-Landing Ma" : 8 ,
      " Paving" : 14 ,
      " Placing bridge girders and beams" : 25 ,
      " Installing plumbing, lighting fixtures" : 184 ,
      " Installing interior walls, ceilings, doors" : 313 ,
      " Swimming pool construction" : 4 ,
      " Other Activities-Installing Ornamental And Archite" : 93 ,
      " Installation Of Decking-Hoisting Bundles" : 12 ,
      " Interior painting and decorating" : 141 ,
      " Temporary work (buildings, facilities)" : 227 ,
      " Loading dock forming and pouring" : 3 ,
      " Steel Erection Of Solid Web-Welding/Burning/Grindi" : 17 ,
      " Waterproofing" : 53 ,
      " Cutting concrete pavement" : 15 ,
      " Exterior masonry" : 306 ,
      " Bituminous concrete placement" : 7 ,
      " Backfilling and compacting" : 17 ,
      " Pouring concrete floor at grade" : 14 ,
      " Exterior cladding" : 76 ,
      " Pouring concrete foundations and walls" : 50 ,
      " Interior tile work (ceramic, vinyl, acoustic)" : 23 ,
      " Forming for piers or pylons" : 15 ,
      " Erecting structural steel" : 396 ,
      " Steel Erection Of Solid Web-Bolting-Up/Detail Work" : 24 ,
      " Placing bridge deck" : 18 ,
      " Steel Erection Of Solid Web-Moving Point To Point" : 9 ,
      " Elevator, escalator installation" : 36 ,
      " Fireproofing" : 37 ,
      "Non record" : 6448 ,
      " Site clearing and grubbing" : 36 ,
      " Interior plumbing, ducting, electrical work" : 173 ,
      " Steel Erection Of Open Web Steel Joists-Bolting-Up" : 10 ,
      " Installation Of Decking-Flashing Of Decking" : 17 ,
      " Erection of coffer dams, caissons" : 5 ,
      " Pouring concrete for piers, and pylons" : 8 ,
      " Exterior carpentry" : 914 ,
      " Interior masonry" : 65 ,
      " Installing underground plumbing conduit" : 18 ,
      " Stripping and curing concrete" : 29 ,
      " Landscaping" : 23 ,
      " Steel Erection Of Solid Web-Plumbing-Up" : 7 ,
      " Seawall construction, riprap placement" : 2 ,
      " Dredging" : 9 ,
      " Installation Of Decking-Final Attachment Deck (Wel" : 21 ,
      " Emplacing reinforcing steel" : 60 ,
      " Demolition" : 294 ,
      " Trenching, installing pipe" : 25 ,
      " Installing equipment (HVAC and other)" : 385 ,
      " Pile driving" : 6 ,
      " Site grading and rock removal" : 11 ,
      " Forming" : 127 ,
      " Steel Erection Of Open Web Steel Joists-Moving Poi" : 6 ,
      " Excavation" : 35 ,
      " Installing windows and doors, glazing" : 106 ,
      " Installation Of Decking-Initial Laying Deck (Incl" : 123} 
    
    fat_cause_classification = { 
      " Struck by falling object/projectile" : 43 ,
      " Fall, other" : 670 ,
      " Fall from/with bucket (aerial lift/basket)" : 173 ,
      " Lifting operations" : 2 ,
      " Electrocution from equipment installation/tool use" : 7 ,
      " Fall from roof" : 2014 ,
      " Crushed/run-over/trapped of operator by operating" : 13 ,
      " Collapse of structure" : 188 ,
      " Wall (earthen) collapse" : 1 ,
      " Trench collapse" : 3 ,
      " Electrocution by touching exposed wire/source" : 14 ,
      " Asphyxiation/inhalation of toxic vapor" : 8 ,
      "Non record" : 6383 ,
      " Fall through opening (other than roof)" : 475 ,
      " Fall from/with platform catwalk (attached to struc" : 142 ,
      " Caught in stationary equipment" : 6 ,
      " Fall from/with structure (other than roof)" : 1208 ,
      " Crushed/run-over of non-operator by operating cons" : 2 ,
      " Crushed/run-over by highway vehicle" : 2 ,
      " Crushed/run-over by construction equipment during" : 3 ,
      " Heat/hypothermia" : 1 ,
      " Fire/explosion" : 3 ,
      " Other" : 56 ,
      " Electric shock, other and unknown cause" : 30 ,
      " Elevator (struck by elevator or counter-weights)" : 2 ,
      " Unloading-loading equipment/material (except by cr" : 3 ,
      " Fall from vehicle (vehicle/construction equipment)" : 101 ,
      " Electrocution by equipment contacting wire" : 12 ,
      " Fall from/with ladder" : 1263 ,
      " Drown, non-lethal fall" : 12 ,
      " Fall from/with scaffold" : 1080}
    
    task_assigned_classification = { 
      "Non record" : 1096 ,
      "Task not regularly assigned" : 1226 ,
      "Task regularly assigned" : 11598}
    
    human_factor_classification = { 
      "Malfunc, Neuromuscular System" : 85 ,
      "No Personal Protective Eq Used" : 13 ,
      "Mater-Handlg Proced. Inappropr" : 388 ,
      "Non record" : 1096 ,
      "Perception Malfunc,Task-Envir." : 204 ,
      "Insuff/Lack/Respiratory Proctect" : 4 ,
      "Equip. Inappropr For Operation" : 1087 ,
      "Lockout/Tagout Proced Malfunc" : 28 ,
      "Safety Devices Removed/Inoper." : 1634 ,
      "Insuff/Lack/Expos/Biologcl Mntrg." : 3 ,
      "Position Inapropriate For Task" : 665 ,
      "Distracting Actions By Others" : 48 ,
      "Insuf/Lack/Protcv Wrk Clthg/Equip" : 872 ,
      "Insuff/Lack/Writn Wrk Prac Prog." : 278 ,
      "No Appropr Protective Clothing" : 2 ,
      "Insuff/Lack/Engineerng Controls" : 338 ,
      "Defective Equipment In Use" : 128 ,
      "Other" : 1954 ,
      "Malfunc In Securing/Warning Op" : 756 ,
      "Misjudgment, Haz. Situation" : 4306 ,
      "Insuff/Lack/Housekeeping Program" : 31}
    
    environment_factor_classification = { 
      "Shear Point Action" : 30 ,
      "Sound Level" : 2 ,
      "Weather, Earthquake, Etc." : 195 ,
      "Flammable Liq/Solid Exposure" : 21 ,
      "Materials Handlg Equip./Method" : 770 ,
      "Temperature +/- Tolerance Lev." : 24 ,
      "Flying Object Action" : 156 ,
      "Work-Surface/Facil-Layout Cond" : 6804 ,
      "Chemical Action/Reaction Expos" : 9 ,
      "Gas/Vapor/Mist/Fume/Smoke/Dust" : 24 ,
      "Radiation Condition" : 12 ,
      "Pinch Point Action" : 21 ,
      "Other" : 3860 ,
      "Non record" : 1096 ,
      "Overpressure/Underpressure" : 13 ,
      "Catch Point/Puncture Action" : 83 ,
      "Illumination" : 30 ,
      "Overhead Moving/Falling Obj Ac" : 741 ,
      "Squeeze Point Action" : 29 }
    
    event_type_classification =   { 
      "Card-Vasc/Resp Fail." : 25 ,
      "Ingestion" : 1 ,
      "Rubbed/Abraded" : 12 ,
      "Rep. Motion/Presure" : 1 ,
      "Fall(Same Level)" : 205 ,
      "Fall(From Elevation)" : 12028 ,
      "Struck By" : 216 ,
      "Shock" : 77 ,
      "Other" : 86 ,
      "Caught In Or Between" : 50 ,
      "Struck Against" : 104 ,
      "Inhalation" : 12 ,
      "Non record" : 1096 ,
      "Absorption" : 3 ,
      "Bite/Sting/Scratch" : 4}
    
    source_injury_classification =  { 
      "Motorcycle" : 2 ,
      "Mists" : 2 ,
      "Air Pressure" : 7 ,
      "Gases" : 5 ,
      "Animal/Ins/Rept/Etc." : 1 ,
      "Bodily Motion" : 1464 ,
      "Fire/Smoke" : 3 ,
      "Elec Apparat/Wiring" : 120 ,
      "Motor Vehicle (Hwy)" : 71 ,
      "Hand Tool (Manual)" : 32 ,
      "Waste Products" : 5 ,
      "Pump/Prime Mover" : 1 ,
      "Materials Handlg Eq." : 264 ,
      "Cleaning Compound" : 5 ,
      "Boxes/Barrels, Etc." : 15 ,
      "Dust/Particles/Chips" : 2 ,
      "Noise" : 3 ,
      "Heat (Envir/Mech)" : 5 ,
      "Wind/Lightning, Etc." : 43 ,
      "Person" : 42 ,
      "Vegetation" : 2 ,
      "Hand Tool (Powered)" : 16 ,
      "Ladder" : 1574 ,
      "Aircraft" : 1 ,
      "Boat" : 6 ,
      "Machine" : 85 ,
      "Water" : 37 ,
      "Boiler/Press Vessel" : 2 ,
      "Metal Products" : 72 ,
      "Chem Liquids/Vapors" : 12 ,
      "Hoisting Apparatus" : 484 ,
      "Motor Vehicle(Indus)" : 88 ,
      "Non record" : 1096 ,
      "Biological Agent" : 2 ,
      "Buildings/Structures" : 2630 ,
      "Drugs/Alcohol" : 10 ,
      "Train/Railroad Equip" : 5 ,
      "Glass" : 7 ,
      "Petroleum Products" : 6 ,
      "Fume" : 2 ,
      "Vibration" : 8 ,
      "Cold (Envir/Mech)" : 4 ,
      "Working Surface" : 3963 ,
      "Dirt/Sand/Stone" : 179 ,
      "Furniture/Furnishing" : 6 ,
      "Other" : 1531}
    
    part_body_classification = { 
      "Arm-Mult" : 384 ,
      "Legs" : 591 ,
      "Chest" : 438 ,
      "Othbodysys" : 237 ,
      "Knee(S)" : 97 ,
      "Head" : 3866 ,
      "Abdomen" : 152 ,
      "Back" : 980 ,
      "Nerve Syst" : 11 ,
      "Multiple" : 2357 ,
      "Hip(S)" : 340 ,
      "Finger(S)" : 24 ,
      "Ear(S)" : 7 ,
      "Upper Arm" : 36 ,
      "Liver" : 24 ,
      "Lower Arm" : 87 ,
      "Neck" : 264 ,
      "Shoulder" : 119 ,
      "Kidney" : 6 ,
      "Eye(S)" : 16 ,
      "Blood" : 5 ,
      "Hand(S)" : 109 ,
      "Reprod-Sys" : 12 ,
      "Bodysystem" : 1212 ,
      "Elbow(S)" : 125 ,
      "Face" : 153 ,
      "Lower Leg" : 175 ,
      "Foot/Ankle" : 654 ,
      "Non record" : 1096 ,
      "Lung" : 43 ,
      "Wrist(S)" : 256 ,
      "Upper Leg" : 44}
    
    proj_type_classification = { 
      "Non record" : 5537 ,
      "Other" : 316 ,
      "New project or new addition" : 4974 ,
      "Maintenance or repair" : 1351 ,
      "Demolition" : 210 ,
      "Alteration or rehabilitation" : 1532}
    
    proj_cost_classification = { 
      "$5,000,000 to $20,000,000" : 718 ,
      "$1,000,000 to $5,000,000" : 1280 ,
      "Under $50,000" : 2415 ,
      "$20,000,000 and over" : 542 ,
      "Non record" : 5565 ,
      "$250,000 to $500,000" : 929 ,
      "$50,000 to $250,000" : 1563 ,
      "$500,000 to $1,000,000" : 908}
    
    end_use_classification = { 
      "Other building" : 1335 ,
      "Powerplant" : 86 ,
      "Other heavy construction" : 83 ,
      "Shoreline development, dam, reservoir" : 7 ,
      "Bridge" : 142 ,
      "Multi-family dwelling" : 932 ,
      "Commercial building" : 2530 ,
      "Sewer/water treatment plant" : 127 ,
      "Powerline, transmission line" : 90 ,
      "Excavation, landfill" : 20 ,
      "Non record" : 5539 ,
      "Refinery" : 31 ,
      "Pipeline" : 26 ,
      "Highway, road, street" : 102 ,
      "Tower, tank, storage elevator" : 248 ,
      "Manufacturing plant" : 264 ,
      "Single family or duplex dwelling" : 2339 ,
      "Contractor's yard/facility" : 19}
    
    